Add Static Range
jreina/ShittyLINQ.js pull request #73
Opened 2018-10-13 02:54 UTC by PieceMaker

Fixes #19.

2018-10-13 23:20 UTC, jreina requested changes

2018-10-13 23:20 UTC, jreina commented on index.d.ts
> +  Range(): Array<number>;
This is missing the `start` and `count` parameters.

2018-10-13 23:20 UTC, jreina commented on src/Range.js
> +  return emptyArray.fill(start).map(_add);
This is pretty clever.

2018-10-14 04:37 UTC, PieceMaker commented on index.d.ts
> +  Range(): Array<number>;
Try now.

2018-10-14 04:41 UTC, jreina approved these changes

2018-10-14 04:41 UTC, merged

2018-10-14 04:41 UTC, jreina commented
Thank you for your contribution. Happy hacking 🎃