Add Sum Overload Accepting Function
jreina/ShittyLINQ.js pull request #75
Opened 2018-10-21 05:27 UTC by PieceMaker

This set of changes adds the overload requested in #26.

2018-10-24 03:53 UTC, jreina requested changes
`predicate` should be `selector` in all cases. You can probably find and replace this but I wanted to try the suggested changes feature.

2018-10-24 03:53 UTC, jreina commented on index.d.ts
> +  Sum(predicate: (x: T) => number): number;
```suggestion
  Sum(selector: (x: T) => number): number;
```

2018-10-24 03:53 UTC, jreina commented on src/Sum.js
> + * @param {((x: T) => number)} predicate
```suggestion
 * @param {((x: T) => number)} selector
```

2018-10-24 03:53 UTC, jreina commented on src/Sum.js
> +function _predicateSum(array, predicate) {
```suggestion
function _predicateSum(array, selector) {
```

2018-10-24 03:53 UTC, jreina commented on src/Sum.js
> +  let predicateResult = array.map(predicate);
```suggestion
  const numbers = array.map(selector);
```
```suggestion
  const xs = array.map(selector);
```

2018-10-24 03:53 UTC, jreina commented on src/Sum.js
> + * @param {((x: T) => number)} predicate
```suggestion
 * @param {((x: T) => number)} selector
```

2018-11-03 03:37 UTC, PieceMaker commented
Changes made.

2019-01-05 01:11 UTC, merged